version: '3.9'

services:
  api:
    build: .
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/${MONGO_NAME}}
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '8000:8000'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo:
    image: mongo:7.0
    command: ['--bind_ip_all']
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand({ ping: 1 }).ok']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
